imageType:
  Original: {}
  Wavelet: {}
  LoG:
    sigma: [1.0, 2.0, 3.0, 4.0, 5.0]
  Square: {}
  SquareRoot: {}
  Logarithm: {}
  Exponential: {} 
  Gradient: {}
  LBP2D: {} 
  LBP3D: {}

setting:
  label: 1                 
  binWidth: 25
  normalize: false           

featureClass:
  firstorder: []
  shape: []
  glcm: []
  glrlm: []
  glszm: []
  gldm: []
  ngtdm: []
